### ISSUE TITLE
Doesn't get past the authorizer?

### ISSUE THREAD

**Issue by vieirai** [nlang/serverless-offline-local-authorizers-plugin#1]
I've created a mock authorizer that just returns some JSON and I can see that it's executing the authorizer mock but then it just hangs and never goes on to execute the lambda code.

Authorizer:
```javascript
const mockAuth = (event) => {
  console.log('My authorizer', event.type);
  return {};
};

module.exports = { mockAuth };
```

dependencies:
```
"serverless": "^1.74.1",
"serverless-offline": "^6.4.0",
"serverless-offline-local-authorizers-plugin": "^1.0.0"
```

extract from serverless.yml:
```yml
functions:
  myFunc:
    name: myFuncName
    handler: src/myFunc.handler
    events:
      - http:
          path: myfunc
          method: post
          authorizer:
            type: TOKEN
            identitySource: method.request.header.myFuncHeader
            arn: XXX
            resultTtlInSeconds: 0
            localAuthorizer:
              name: "mockAuth"
              type: "token"
```

Another odd thing I noticed, is that it seems to call the authorizer twice even though I only made one request to the API 🤔

Not sure if I'm doing something wrong, but any help is appreciated!
