### ISSUE TITLE
Plugin searches local-authorizers.js, but executes local-authorizers.py, with runtime: python

### ISSUE THREAD

**Issue by huonw** [nlang/serverless-offline-local-authorizers-plugin#10]
This plugin is great, thank you!

We're using it in a Python Serverless project. That is, our `serverless.yml` file includes:

```yaml
plugins:
  - serverless-python-requirements
  - serverless-offline
  - serverless-offline-local-authorizers-plugin

...

provider:
  name: aws
  runtime: python3.8
  ...

...
```

This means that all of our functions' `handler`s refer to python function, and this seems to apply the functions generated by this plugin too (with handlers `local-authorizer.<name>`). The Python runtime specification seems to mean that Serverless looks in `local-authorizers.py` to find this function. However, this plugin always loads `local-authorizers.js` to generate the handler functions.

For example, suppose there's a function like the example in the readme:

```yml
functions:
  myFunction:
    handler: myFunction.handler
    events:
      - http:
          path: /my/api/path
          method: GET
          authorizer:
            type: CUSTOM
            authorizerId: abcjfk
            localAuthorizer:
              name: "mylocalAuthProxyFn"
              type: "request"
```

If one places the authorizer just in `local-authorizers.js` (e.g. `module.exports = {mylocalAuthProxyFn: null};` as a minimal example) leads to an `ModuleNotFoundError: No module named 'local-authorizers'` error, from Python:

<details><summary>Click for full error</summary>

```
[offline] Loading handler... (.../api/local-authorizers)
Traceback (most recent call last):
  File ".../api/node_modules/serverless-offline/dist/lambda/handler-runner/python-runner/invoke.py", line 76, in <module>

    module = import_module(args.handler_path.replace(os.sep, '.'))
  File "/Users/huon/.pyenv/versions/3.8.7/lib/python3.8/importlib/__init__.py", line 127, in import_module

    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import

  File "<frozen importlib._bootstrap>", line 991, in _find_and_load

  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked

ModuleNotFoundError: No module named 'local-authorizers'
```

</details>

Placing it just in `local-authorizers.py` (e.g. `def mylocalAuthProxyFn(): pass` as a minimal example) leads to this plugin having nothing to do:

```
Serverless: Invoke offline:local-authorizers
serverless-offline-local-authorizers-plugin: No local authorizers found.
```

Thus, we're having to place the authoriser in two files: 

- a stub in `local-authorizers.js`, to ensure the plugin generates the local authorizers
- the real implementation in `local-authorizers.py` since that is what is executed

It'd be great if the plugin didn't require two files in Python projects. I can think of a few options:

- ensuring that `local-authorizers.js` was always always used for execution
- looking in `local-authorizers.py` to define the authorizers
- collecting all of the `localAuthorizer.name` values and defining the functions based on those, hoping they exist (but the requests should fail if they don't)

Thanks again for the plugin!
