### ISSUE TITLE
How to integrate the plugin with Cognito?

### ISSUE THREAD

**Issue by turakvlad** [nlang/serverless-offline-local-authorizers-plugin#3]
Hey! First of all, I would like to thank you for this plugin. It is really useful, thanks!

May I ask for any samples of how I can write `local-authorizers.js` so it uses Cognito User Pool. I am not really sure I understand what you meant by this _call Cognito to mock your Cognito Authorizer_.

My `serverless.yml`:

```
functions:
  courses-list:
    handler: services/courses/endpoints/list.handler
    events:
      - http:
          path: api/v1/courses
          method: get
          authorizer:
            arn: arn:aws:cognito-idp:eu-central-1:xxxxxxxxxx:userpool/eu-central-1_xxxxxxxxx
            localAuthorizer:
              name: mylocalAuthProxyFn
              type: request
```

Thanks for any help!
