### ISSUE TITLE
Set Up `serverless-offline-local-authorizers-plugin: Unable to load local authorizers from...`

### ISSUE THREAD

**Issue by ryancarville** [nlang/serverless-offline-local-authorizers-plugin#4]
Hello,
I am excited to get this up and running but have a littl issue.  Can you expalin what this means:
```
serverless-offline-local-authorizers-plugin: Unable to load local authorizers from...
```
Here is a example of one of my endpoints:
```
createLogout:
    handler: functions/index.createLogout
    events:
      - http:
          path: logouts
          method: post
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId:
              Ref: Authorizer1
          localAuthorizer:
            name: "mylocalAuthProxyFn"
            type: "request"

```
Here is the local-authorizers.js
```
const AWS = require("aws-sdk");
const mylocalAuthProxyFn = async (event, context) => {

  const lambda = new AWS.Lambda();
  const result = await lambda.invoke({
    FunctionName: "CreateAuthorizationLambdaFunction",
    InvocationType: "RequestResponse",
    Payload: JSON.stringify(event),
  }).promise();

  if (result.StatusCode === 200) {
    return JSON.parse(result.Payload);
  }

  throw Error("Authorizer error");
};

module.exports = { mylocalAuthProxyFn };
```
