### ISSUE TITLE
serverless-offline-local-authorizers-plugin: Invlalid or unknown local authorizer 'undefined'

### ISSUE THREAD

**Issue by jon-wade** [nlang/serverless-offline-local-authorizers-plugin#7]
I have a serverless.yml with multiple functions defined that produce apigateway endpoints. Some of the functions have custom authorizers and some don't (i.e. they are publicly accessible). I'm using the local-authorizers-plugin and when I spin up serverless offline, I'm getting the following error message `serverless-offline-local-authorizers-plugin: Invlalid or unknown local authorizer 'undefined'`. This occurs only when I define a function without an authorizer. So for example:

```
functions:
  someFunction:
    handler: foo/bar/index.someFunction
    name: some-function-${opt:stage, self:provider.stage}
    description: Blah blah
    events:
      - http:
          path: /foo/bar
          method: post
          cors: true
```

Will produce the error but:

```
functions:
  someFunction:
    handler: foo/bar/index.someFunction
    name: some-function-${opt:stage, self:provider.stage}
    description: Blah blah
    events:
      - http:
          path: /foo/baa
          method: post
          cors: true
          authorizer:
            type: CUSTOM
            resultTtlInSeconds: 0
            authorizerId: ${self:provider.environment.some_ref}
            identitySource: method.request.header.Authorization
            localAuthorizer:
              name: authenticator
              type: request
```

Will not. The endpoint without the local-authorizer seems to work fine despite the error, as do the endpoints with the local-authorizer. So not sure why the error is appearing.
